// <auto-generated />
namespace elcubo9.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class TableNumberToString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableNumberToString));
        
        string IMigrationMetadata.Id
        {
            get { return "201410221300504_TableNumberToString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
